dist: xenial
language: python
python:
- '3.6'
- '3.7'
virtualenv:
  system_site_packages: false
install:
- pip install -r requirements.txt
- pip install coveralls pytest
- python setup.py install
script:
#- source activate test-environment
- coverage run --source=dsf setup.py test
after_success: coveralls
branches:
  only:
  - master
  - /v\d+\.\d+/
